# Generated by Django 5.0.7 on 2024-08-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sys", "0002_alter_userinfo_create_time_alter_userinfo_depart"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrettyNum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=11, verbose_name="号码")),
                ("price", models.IntegerField(verbose_name="价格")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "一级"), (2, "二级"), (3, "三级"), (4, "四级")],
                        default=1,
                        verbose_name="等级",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未占用"), (1, "已占用")], default=0, verbose_name="占用情况"
                    ),
                ),
            ],
        ),
    ]
