# Generated by Django 5.0.7 on 2024-08-11 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sys", "0004_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=64, verbose_name="订单号")),
                ("title", models.CharField(max_length=32, verbose_name="名称")),
                ("price", models.IntegerField(verbose_name="价格")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "待支付"), (1, "已支付")], default=0, verbose_name="状态"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_sys.admin",
                        verbose_name="管理员",
                    ),
                ),
            ],
        ),
    ]
